steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "asia.gcr.io/$PROJECT_ID/aus_rental:$COMMIT_SHA", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "asia.gcr.io/$PROJECT_ID/aus_rental:$COMMIT_SHA"]
logsBucket: 'gs://cloudbuild_logs_bucket'
