FROM python:3.10-slim

ENV PYTHONUNBUFFERED True

ENV APP_HOME /app
WORKDIR $APP_HOME

COPY src/ src/
RUN mkdir -p output
COPY requirements.txt requirements.txt

# Install production dependencies.
RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["bash","src/entrypoint.sh"]
